[package]
name = "fake-feature"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { version = "0.3", features = ["wrap_help"] }
fake = { version = "2.4", features = ["chrono", "uuid"] }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
csv = "1.1"
chrono = { version = "0.4", features = ["serde"] }
strum = { version = "0.23.0", features = ["derive"] }
